# Generated by Django 5.2.8 on 2026-03-08 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_feecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZATCAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_trn', models.CharField(max_length=20, unique=True, verbose_name='Tax Registration Number (TRN)')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('organization_name_ar', models.CharField(blank=True, max_length=255, verbose_name='Organization Name (Arabic)')),
                ('organization_email', models.EmailField(max_length=254, verbose_name='Organization Email')),
                ('organization_phone', models.CharField(max_length=20, verbose_name='Organization Phone')),
                ('organization_address', models.TextField(verbose_name='Organization Address')),
                ('organization_city', models.CharField(default='Riyadh', max_length=100, verbose_name='City')),
                ('certificate_path', models.CharField(blank=True, help_text='Path to ZATCA certificate file', max_length=255, verbose_name='Certificate Path')),
                ('private_key_path', models.CharField(blank=True, help_text='Path to private key file', max_length=255, verbose_name='Private Key Path')),
                ('use_sandbox', models.BooleanField(default=True, verbose_name='Use Sandbox Environment')),
                ('api_username', models.CharField(blank=True, max_length=255, verbose_name='API Username')),
                ('api_password', models.CharField(blank=True, max_length=255, verbose_name='API Password')),
                ('auto_submit', models.BooleanField(default=True, verbose_name='Auto Submit Invoices to ZATCA')),
                ('auto_sign', models.BooleanField(default=True, verbose_name='Auto Sign Invoices')),
                ('generate_qr', models.BooleanField(default=True, verbose_name='Generate QR Code')),
                ('is_configured', models.BooleanField(default=False, verbose_name='Configuration Complete')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync with ZATCA')),
            ],
            options={
                'verbose_name': 'ZATCA Configuration',
                'verbose_name_plural': 'ZATCA Configurations',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_compliance_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('rejected', 'Rejected')], max_length=50, verbose_name='ZATCA Compliance Status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_submission_uuid',
            field=models.CharField(blank=True, max_length=100, verbose_name='ZATCA Submission UUID'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_submitted',
            field=models.BooleanField(default=False, verbose_name='Submitted to ZATCA'),
        ),
        migrations.CreateModel(
            name='ZATCASubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('rejected', 'Rejected'), ('error', 'Error')], default='pending', max_length=20)),
                ('xml_content', models.TextField(verbose_name='XML Content')),
                ('xml_signature', models.TextField(blank=True, verbose_name='Digital Signature')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='zatca_qr_codes/', verbose_name='QR Code')),
                ('zatca_response', models.JSONField(blank=True, null=True, verbose_name='ZATCA API Response')),
                ('zatca_uuid', models.CharField(blank=True, max_length=100, verbose_name='ZATCA UUID')),
                ('zatca_status', models.CharField(blank=True, max_length=50, verbose_name='ZATCA Status')),
                ('compliance_invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Compliance Invoice Number')),
                ('is_compliant', models.BooleanField(default=False, verbose_name='Is Compliant')),
                ('compliance_errors', models.JSONField(blank=True, null=True, verbose_name='Compliance Errors')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_method', models.CharField(choices=[('api', 'API'), ('portal', 'Portal'), ('manual', 'Manual')], default='api', max_length=20, verbose_name='Submission Method')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zatca_submission', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'ZATCA Submission',
                'verbose_name_plural': 'ZATCA Submissions',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
    ]
