"""
Django settings for Database1 project.
made by Inam Khan - 2024-06-01
Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment, fall back to hardcoded value for local development
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-&0fb*y7-*vj22&gm__)cu(^4u*vs7f3g+06ryhk%*+@6+5sp=-')

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable so production can disable debug easily.
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Allow hosts configuration via environment, default to wildcard for dev
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Optional: force the application to only operate for a single school.
# Provide either the school name or code; matching is case-insensitive and
# partial. Useful when deploying for one institution such as "Alkawthar".
# If empty or not set, normal multi-school behavior applies.
FORCE_SCHOOL_IDENTIFIER = os.getenv('FORCE_SCHOOL_IDENTIFIER', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'tailwind',
    'theme',
    
    # Accountant Apps Only
    'accounts',  # User authentication
    'dashboard',  # Main dashboard
    'schools',  # Multi-School/Organization Management
    'students',  # Minimal student model (for billing only)
    'accounting',  # Advanced Accounting (General Ledger, Journal Entries)
    'billing',  # Billing and invoices
    'reports',  # Financial reports
    'settings_app',  # Settings management
]
TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'schools.middleware.SchoolContextMiddleware',  # Multi-school context
    'schools.middleware.SchoolAccessMiddleware',  # School-level access control
]

ROOT_URLCONF = 'Database1.urls'

CSRF_TRUSTED_ORIGINS = [
    "https://*.trycloudflare.com"
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounting.context_processors.accounting_permissions',  # Accounting permissions
            ],
        },
    },
]

WSGI_APPLICATION = 'Database1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
import sys

# Use sqlite in-memory database when running tests to avoid needing PostgreSQL permissions
if 'test' in sys.argv or 'pytest' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'mydb2',
            'USER': 'myuser',
            'PASSWORD': 'mypassword',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'  # Default language

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_I18N = True  # Enable internationalization
USE_L10N = True  # Enable localized formatting
USE_TZ = True

TIME_ZONE = 'Asia/Riyadh'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Authentication Settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'




